name: table_view_ex
description: A more feature rich data table control built on TableView with sortable, resizable and rearrangeable headers and customized styling
version: 0.1.2
homepage: https://github.com/cnayan/table_view_ex
repository: https://github.com/cnayan/table_view_ex

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter: 
    sdk: flutter
  two_dimensional_scrollables: ^0.3.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: 'ViewOnlyTableViewEx table control with sortable, resizable and rearrangeable headers with customized styling'
    path: screenshots/table_view_ex_example1.png
